global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - "rules/*.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'consul'
    consul_sd_configs:
      - server: 'consul-server1:8500'
        services: []
    relabel_configs:
      - source_labels: [__meta_consul_service]
        target_label: service
      - source_labels: [__meta_consul_node]
        target_label: node
      - source_labels: [__meta_consul_dc]
        target_label: dc

  - job_name: 'consul-exporter'
    static_configs:
      - targets: ['consul-exporter:9107']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'consul-servers'
    static_configs:
      - targets:
          - 'consul-server1:8500'
          - 'consul-server2:8500'
          - 'consul-server3:8500'
    metrics_path: /v1/agent/metrics
    params:
      format: ['prometheus']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'pyroscope'
    static_configs:
      - targets: ['pyroscope:4040']
    metrics_path: /metrics

  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']