groups:
- name: consul_alerts
  rules:
  - alert: ConsulServerDown
    expr: up{job="consul-servers"} == 0
    for: 1m
    labels:
      severity: critical
      service: consul
    annotations:
      summary: "Consul服务器宕机 ({{ $labels.instance }})"
      description: "Consul服务器 {{ $labels.instance }} 已经宕机超过1分钟\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

  - alert: ConsulClusterLeaderLost
    expr: consul_raft_leader{job="consul-exporter"} == 0
    for: 30s
    labels:
      severity: critical
      service: consul
    annotations:
      summary: "Consul集群失去Leader"
      description: "Consul集群当前没有Leader，这可能导致服务发现和配置管理功能不可用\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

  - alert: ConsulClusterNodesDown
    expr: count(up{job="consul-servers"} == 0) >= 1
    for: 1m
    labels:
      severity: warning
      service: consul
    annotations:
      summary: "多个Consul节点宕机"
      description: "{{ $value }} 个Consul节点已经宕机，集群仍然可用但冗余性降低\n  LABELS = {{ $labels }}"

  - alert: ConsulServiceHealthCheckFailing
    expr: consul_catalog_service_node_healthy{job="consul-exporter"} == 0
    for: 2m
    labels:
      severity: warning
      service: consul
    annotations:
      summary: "服务健康检查失败 ({{ $labels.service_name }})"
      description: "服务 {{ $labels.service_name }} 在节点 {{ $labels.node }} 上的健康检查失败\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

  - alert: PrometheusTargetMissing
    expr: up == 0
    for: 1m
    labels:
      severity: warning
      service: monitoring
    annotations:
      summary: "Prometheus目标丢失 ({{ $labels.instance }})"
      description: "目标 {{ $labels.instance }} 的监控数据采集失败\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

  - alert: HostHighCpuLoad
    expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
    for: 5m
    labels:
      severity: warning
      service: system
    annotations:
      summary: "主机CPU负载高 ({{ $labels.instance }})"
      description: "主机CPU使用率超过80%\n  VALUE = {{ $value }}%\n  LABELS = {{ $labels }}"

  - alert: HostOutOfMemory
    expr: node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100 < 10
    for: 5m
    labels:
      severity: warning
      service: system
    annotations:
      summary: "主机内存不足 ({{ $labels.instance }})"
      description: "主机可用内存低于10%\n  VALUE = {{ $value }}%\n  LABELS = {{ $labels }}"

  - alert: HostOutOfDiskSpace
    expr: (node_filesystem_avail_bytes{mountpoint="/",fstype!="rootfs"} / node_filesystem_size_bytes{mountpoint="/",fstype!="rootfs"} * 100) < 10
    for: 5m
    labels:
      severity: warning
      service: system
    annotations:
      summary: "主机磁盘空间不足 ({{ $labels.instance }})"
      description: "主机根分区可用空间低于10%\n  VALUE = {{ $value }}%\n  LABELS = {{ $labels }}"