---
log-level: "debug"

storage:
  path: "/var/lib/pyroscope"
  retention: 30d

api-server:
  listen-addr: ":4040"

scrape-configs:
  - job-name: pyroscope
    enabled-profiles:
      [cpu, mem, goroutines, mutex, block]
    spy-name: gospy
    application-name: pyroscope.server.{profile_name}

  - job-name: consul-services
    enabled-profiles:
      [cpu, mem, goroutines, mutex, block]
    spy-name: gospy
    consul:
      server: "consul-server1:8500"
      services: []
      tags: ["pyroscope"]
    application-name-config:
      from-label: "service-name"
      add-suffix: ".{profile_name}"

security:
  no-auth: true
